apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: dev-mapping

namespace: dev
namePrefix: dev-
replicas:
- name: app-1-deployment
  count: 1

resources:
  - ../../base/app-1/
  - ../../base/ingress/

patches:
- target:
    kind: Ingress
    name: app-ingress
  path: dev-ingress-patch.json
